CRITICAL - 2020-08-26 14:30:44 --> Undefined index: usuario_covid_logado
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-26 14:33:34 --> Undefined index: arquivo
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(34): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2020-08-26 14:33:39 --> Too few arguments to function App\Controllers\Covid::acao(), 0 passed in C:\xampp\htdocs\arthur\system\CodeIgniter.php on line 914 and exactly 1 expected
#0 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao()
#1 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2020-08-26 19:45:01 --> Undefined index: cd_setor
#0 C:\xampp\htdocs\arthur\app\Views\setor\setor.php(30): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 30, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('setor/setor', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Setor.php(22): view('setor/setor')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Setor->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Setor))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-26 21:00:30 --> Undefined variable: data
#0 C:\xampp\htdocs\arthur\app\Models\M_Covid.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(125): App\Models\M_Covid->AtualizarFonteCovid('4')
#2 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(44): App\Controllers\Covid->AtualizarFonte(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('atualizar-site-...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-26 21:00:51 --> oci_execute(): ORA-00933: SQL command not properly ended
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'oci_execute(): ...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\arthur\app\Models\M_Covid.php(100): oci_execute(Resource id #105)
#2 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(125): App\Models\M_Covid->AtualizarFonteCovid('4')
#3 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(44): App\Controllers\Covid->AtualizarFonte(Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('atualizar-site-...')
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-26 21:00:51 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "{0}". in C:\xampp\htdocs\arthur\system\Format\Exceptions\FormatException.php:9
Stack trace:
#0 C:\xampp\htdocs\arthur\system\Format\JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(414): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\arthur\system\API\ResponseTrait.php(134): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\arthur\system\Debug\Exceptions.php(166): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-08-26 21:09:31 --> Undefined variable: timestamp
#0 C:\xampp\htdocs\arthur\app\Models\M_Covid.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(125): App\Models\M_Covid->AtualizarFonteCovid('4')
#2 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(44): App\Controllers\Covid->AtualizarFonte(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('atualizar-site-...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-26 21:10:21 --> Undefined variable: timestamp
#0 C:\xampp\htdocs\arthur\app\Models\M_Covid.php(98): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 98, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(125): App\Models\M_Covid->AtualizarFonteCovid('4')
#2 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(44): App\Controllers\Covid->AtualizarFonte(Array)
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('atualizar-site-...')
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2020-08-26 21:24:27 --> Creating default object from empty value
#0 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(89): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Creating defaul...', 'C:\\xampp\\htdocs...', 89, Array)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(34): App\Controllers\Covid->CadastraCovid(Array, Array)
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->acao('adicionar-covid')
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-26 22:11:36 --> Illegal string offset 'setor'
#0 C:\xampp\htdocs\arthur\app\Views\include\header.php(50): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Illegal string ...', 'C:\\xampp\\htdocs...', 50, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('include/header', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(20): view('include/header', Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-26 22:13:10 --> Undefined index: id_setor
#0 C:\xampp\htdocs\arthur\app\Views\include\header.php(50): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 50, Array)
#1 C:\xampp\htdocs\arthur\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('include/header', Array, true)
#3 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(20): view('include/header', Array)
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#5 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#6 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2020-08-26 22:14:04 --> syntax error, unexpected '<'
#0 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('include/menu', Array, true)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(21): view('include/menu')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-26 22:14:50 --> syntax error, unexpected end of file
#0 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('include/menu', Array, true)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(21): view('include/menu')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2020-08-26 22:15:33 --> syntax error, unexpected end of file
#0 C:\xampp\htdocs\arthur\system\Common.php(1087): CodeIgniter\View\View->render('include/menu', Array, true)
#1 C:\xampp\htdocs\arthur\app\Controllers\Covid.php(21): view('include/menu')
#2 C:\xampp\htdocs\arthur\system\CodeIgniter.php(914): App\Controllers\Covid->index()
#3 C:\xampp\htdocs\arthur\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Covid))
#4 C:\xampp\htdocs\arthur\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\arthur\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
